[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[black]
line-length = 100
target-version = ['py310']

[tool.docformatter]
recursive = true
wrap-summaries = 100
wrap-descriptions = 100
